### ISSUE TITLE
[1.16.5] Awful stutter/momentary freezing on world start

### ISSUE THREAD

**Issue by Kaleidio** [MarkusBordihn/BOs-Advancements-Tracker#8]
**Describe the bug**
Whilst using this mod in a modpack that provides a lot of advancements, the mod will cause the render to randomly freeze for a long time (sometimes more than once) whilst generating the world's chunks, alongside a ton of stutter.  the stutter disappears after the world is done loading everything.

**To Reproduce**
1. Install any large pack that is relatively stable on its own
2. Install Advancement Tracker
3. Create a new world and watch the stutter/freezing.

**Expected behavior**
There should be no long term freeze.  it might be optimal to see if there's a way to either speedup the advancement list building process, or find a way to shift advancement/gui loading to a different thread/stage of the loading process, so long as render does not pause during this setup.

**Additional context**
Again, requires a modpack with many new advancements to be installed, does not seem as rambunctiously long on lag with vanilla.

**Comment by MarkusBordihn** [comment]
Thanks for the report unfortunately there is not a lot which i could do in this case for the following reasons.

- Because it's a client side mod, I depend on the client side events, so I'm not able to defer the event registration.
- The client side event is only triggered on the world load by the server -> client, so I'm not able to re-trigger it at a later point from the client side.

I will do the following in this case:

- Adding a additional logging information about the loading time / processing time of the mod.
- Try to optimize / minimize all processing during the load event.

Could you let me know the name of the mod pack, if this is on curse-forge, to have something for testing ? Thanks.

**Comment by Kaleidio** [comment]
Kaleidio's Battle Pack is the one I used for testing tho it's not exactly optimized as is at the moment.  another good pack would be Better Minecraft as that has a lot of advancements.

**Comment by MarkusBordihn** [comment]
Just released a new optimized version, which shows a 40% better performance than the former version.
It could take some time until it will be visible over: https://www.curseforge.com/minecraft/mc-mods/advancements-tracker/files/3604996 .
Please make sure to disable the "screenshot" support for testing, because I notice it could cause a lag with granting advancements over `advancement grant @a ...`.

But besides of the new changes, there is unfortunately not a lot what I could do for the 1.16.5 version.

**Comment by Kaleidio** [comment]
I will attempt to test with this tomorrow.  Thank you

**Comment by Kaleidio** [comment]
I understand that your mod provides a feature to screenshot achievements.  This was actually a duplicated feature provided by another mod called Advancement Plaques.  Said mod also released a new mixin that makes file writing the screenshot file asynchronous which helps will screenshot freezes.  Thus I will keep your version turned off to prevent even more stutter.

your optimizations were helpful. thank you.
